const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

const COOKIES_FILE = path.resolve(__dirname, 'cookies.txt');
const LOGIN_URL = 'https://www.youtube.com/';

async function exportCookiesToNetscapeFormat(cookies) {
  let output = `# Netscape HTTP Cookie File\n# This file is generated by refresh-cookies.js\n\n`;

  for (const cookie of cookies) {
    // domain, flag, path, secure, expiration, name, value
    const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
    const flag = cookie.hostOnly ? 'FALSE' : 'TRUE';
    const path = cookie.path;
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiration = cookie.expires ? Math.floor(new Date(cookie.expires).getTime() / 1000) : 2147483647;
    const name = cookie.name;
    const value = cookie.value;

    output += [domain, flag, path, secure, expiration, name, value].join('\t') + '\n';
  }

  return output;
}

async function main() {
  // const browser = await puppeteer.launch({
  //   headless: true,
  //   args: ['--no-sandbox', '--disable-setuid-sandbox'],
  // });

  const browser = await puppeteer.launch({
    headless: 'new', // or true for older versions
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
  });
  

  const page = await browser.newPage();

  // Load previous cookies if available (optional, here you start fresh)
  if (fs.existsSync(COOKIES_FILE)) {
    // You can implement loading cookies if needed
  }

  console.log('Opening YouTube login page. Please login manually if required.');
  await page.goto(LOGIN_URL, { waitUntil: 'networkidle2' });

  // Wait 60 seconds for manual login (you can increase if needed)
  await new Promise(resolve => setTimeout(resolve, 60000));

  // Get cookies after login
  const cookies = await page.cookies();

  // Export cookies in Netscape format
  const netscapeCookies = await exportCookiesToNetscapeFormat(cookies);

  fs.writeFileSync(COOKIES_FILE, netscapeCookies);

  console.log('Cookies exported to', COOKIES_FILE);

  await browser.close();
}

main().catch(console.error);
