// const puppeteer = require('puppeteer');
// const fs = require('fs');
// const path = require('path');

// // scripts/getYoutubeCookies.js
// import puppeteer from "puppeteer";
// import fs from "fs";

// const COOKIES_FILE = path.resolve(__dirname, 'cookies.txt');
// const LOGIN_URL = 'https://www.youtube.com/';

// async function exportCookiesToNetscapeFormat(cookies) {
//   let output = `# Netscape HTTP Cookie File\n# This file is generated by refresh-cookies.js\n\n`;

//   for (const cookie of cookies) {
//     // domain, flag, path, secure, expiration, name, value
//     const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
//     const flag = cookie.hostOnly ? 'FALSE' : 'TRUE';
//     const path = cookie.path;
//     const secure = cookie.secure ? 'TRUE' : 'FALSE';
//     const expiration = cookie.expires ? Math.floor(new Date(cookie.expires).getTime() / 1000) : 2147483647;
//     const name = cookie.name;
//     const value = cookie.value;

//     output += [domain, flag, path, secure, expiration, name, value].join('\t') + '\n';
//   }

//   return output;
// }

// async function main() {
//   // const browser = await puppeteer.launch({
//   //   headless: true,
//   //   args: ['--no-sandbox', '--disable-setuid-sandbox'],
//   // });

//   const browser = await puppeteer.launch({
//     headless: 'new', // or true for older versions
//     args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
//   });
  

//   const page = await browser.newPage();

//   // Load previous cookies if available (optional, here you start fresh)
//   if (fs.existsSync(COOKIES_FILE)) {
//     // You can implement loading cookies if needed
//   }

//   console.log('Opening YouTube login page. Please login manually if required.');
//   await page.goto(LOGIN_URL, { waitUntil: 'networkidle2' });

//   // Wait 60 seconds for manual login (you can increase if needed)
//   await new Promise(resolve => setTimeout(resolve, 60000));

//   // Get cookies after login
//   const cookies = await page.cookies();

//   // Export cookies in Netscape format
//   const netscapeCookies = await exportCookiesToNetscapeFormat(cookies);

//   fs.writeFileSync(COOKIES_FILE, netscapeCookies);

//   console.log('Cookies exported to', COOKIES_FILE);

//   await browser.close();
// }

// main().catch(console.error);




// async function getYoutubeCookies() {
//     const browser = await puppeteer.launch({ headless: true });
//     const page = await browser.newPage();

//     // Go to YouTube login
//     await page.goto("https://accounts.google.com/signin/v2/identifier?service=youtube", {
//         waitUntil: "networkidle2",
//     });

//     // Email
//     await page.type('input[type="email"]', process.env.GOOGLE_EMAIL);
//     await page.click('#identifierNext');
//     await page.waitForTimeout(2000);

//     // Password
//     await page.type('input[type="password"]', process.env.GOOGLE_PASSWORD);
//     await page.click('#passwordNext');
//     await page.waitForNavigation({ waitUntil: "networkidle2" });

//     // Get cookies
//     const cookies = await page.cookies();
//     fs.writeFileSync("youtube_cookies.json", JSON.stringify(cookies, null, 2));

//     console.log("✅ Cookies saved to youtube_cookies.json");
//     await browser.close();
// }

// getYoutubeCookies();






// refreshCookies.js
// refresh-cookies.js
import puppeteer from "puppeteer";
import fs from "fs";
import path from "path";
import dotenv from "dotenv";

dotenv.config(); // Load .env variables

const COOKIES_PATH = path.resolve(process.cwd(), "cookies.txt");
const LOGIN_URL = "https://accounts.google.com/ServiceLogin?service=youtube";

// Read credentials from .env
const YOUTUBE_EMAIL = process.env.GOOGLE_EMAIL;
const YOUTUBE_PASSWORD = process.env.GOOGLE_PASSWORD;

if (!YOUTUBE_EMAIL || !YOUTUBE_PASSWORD) {
  console.error("❌ Missing GOOGLE_EMAIL or GOOGLE_PASSWORD in .env file");
  process.exit(1);
}

// Convert cookies to Netscape format
async function exportCookiesToNetscapeFormat(cookies) {
  let output = `# Netscape HTTP Cookie File\n# This file is generated by refresh-cookies.mjs\n\n`;

  for (const cookie of cookies) {
    const domain = cookie.domain.startsWith(".") ? cookie.domain : "." + cookie.domain;
    const flag = cookie.hostOnly ? "FALSE" : "TRUE";
    const pathVal = cookie.path;
    const secure = cookie.secure ? "TRUE" : "FALSE";

    // ✅ Fix for yt-dlp: if expires is -1 or missing, use year 2038
    const expiration =
      !cookie.expires || cookie.expires < 0
        ? 2147483647
        : Math.floor(new Date(cookie.expires).getTime() / 1000);

    const name = cookie.name;
    const value = cookie.value;

    output += [domain, flag, pathVal, secure, expiration, name, value].join("\t") + "\n";
  }

  return output;
}

export async function refreshCookies() {
  console.log("🌐 Launching Chrome for YouTube login...");

  const browser = await puppeteer.launch({
    headless: false,
    executablePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", // Use real Chrome on local
    args: [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-blink-features=AutomationControlled"
    ],
  });

  const page = await browser.newPage();

  // Make browser look human-like
  await page.setUserAgent(
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
    "(KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
  );
  await page.setViewport({ width: 1366, height: 768 });

  await page.goto(LOGIN_URL, { waitUntil: "networkidle2" });

  console.log("🔹 Logging in with provided credentials...");

  // Enter email
  await page.type("input[type='email']", YOUTUBE_EMAIL, { delay: 100 });
  await page.click("#identifierNext");
  await new Promise(res => setTimeout(res, 2000));

  // Enter password
  await page.waitForSelector("input[type='password']", { visible: true });
  await page.type("input[type='password']", YOUTUBE_PASSWORD, { delay: 100 });
  await page.click("#passwordNext");

  // Wait for login success (YouTube home page)
  await page.waitForNavigation({ waitUntil: "networkidle2" });

  console.log("✅ Logged in successfully, saving cookies...");

  const cookies = await page.cookies();
  const netscapeCookies = await exportCookiesToNetscapeFormat(cookies);

  fs.writeFileSync(COOKIES_PATH, netscapeCookies);
  console.log(`🍪 Cookies saved to ${COOKIES_PATH}`);

  await browser.close();
}

// Run directly
if (process.argv[1] === new URL(import.meta.url).pathname) {
  (async () => {
    try {
      await refreshCookies();
      console.log("🎉 Cookie refresh completed successfully!");
    } catch (err) {
      console.error("❌ Error refreshing cookies:", err);
    }
  })();
}
